# Generated by Django 4.2.3 on 2023-08-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_deportista_federado_deportista_edad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['nombre'], 'verbose_name': 'Club', 'verbose_name_plural': 'Clubes'},
        ),
        migrations.AlterModelOptions(
            name='deporte',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='deportista',
            options={'ordering': ['apellido']},
        ),
        migrations.AlterModelOptions(
            name='entrenador',
            options={'ordering': ['apellido'], 'verbose_name': 'Entrenador', 'verbose_name_plural': 'Entrenadores'},
        ),
    ]
